### ISSUE TITLE
Error thrown out when Deploy Dynamics 365 Package and Data using Package Deployer

### ISSUE THREAD

**Issue by Amos-lin** [WaelHamze/dyn365-ce-devops-sample#1]
When execute the task of Package Deployer, encounter the following error.
Check the URL below, the ImportExtension Class doesn't have the method of "get_CrmSvc()".
https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/dn688939%28v%3dcrm.8%29

Would you please have a check if it is a bug?

2018-10-13T09:06:25.5627893Z ##[section]Starting: Deploy Dynamics 365 Package and Data using Package Deployer
2018-10-13T09:06:25.5630830Z ==============================================================================
2018-10-13T09:06:25.5630895Z Task         : MSCRM Package Deployer
2018-10-13T09:06:25.5631202Z Description  : Deploys a CRM Package using the CRM Package Deployer PowerShell Cmdlets
2018-10-13T09:06:25.5631373Z Version      : 10.0.5
2018-10-13T09:06:25.5631418Z Author       : Wael Hamze
2018-10-13T09:06:25.5631479Z Help         : For more information on CRM Package Deployer: https://technet.microsoft.com/en-us/library/dn647420.aspx
2018-10-13T09:06:25.5631528Z ==============================================================================
2018-10-13T09:06:41.0417107Z PackageDeployer Information: 8 : Starting Config Reading process:
2018-10-13T09:06:41.0517753Z PackageDeployer Information: 8 : ReadingConfig from : D:\A\R1\A\_PRIMARY BUILD\DROP\DEPLOYMENTPACKAGE\BIN\RELEASE\PkgFolder\ImportConfig.xml
2018-10-13T09:06:41.0525176Z PackageDeployer Verbose: 16 : Unpacking config
2018-10-13T09:06:41.0868680Z PackageDeployer Information: 8 : Reading Solutions.. Please wait
2018-10-13T09:06:41.1799122Z PackageDeployer Verbose: 16 : Cleaning up Temp Working Directory - C:\Users\VssAdministrator\AppData\Local\Temp\zutkui5f.ogz
2018-10-13T09:06:41.1949873Z PackageDeployer Information: 8 : Found One Custom Extension
2018-10-13T09:06:41.3801921Z PackageDeployer Information: 8 : Deployment Target Organization ID: a95e657e-c30f-4b31-acb9-62f5043e5dcd
2018-10-13T09:06:41.3808846Z PackageDeployer Information: 8 : Deployment Target Organization UniqueName: orgbfb449af
2018-10-13T09:06:41.3814884Z PackageDeployer Information: 8 : Deployment Target Organization Version: 9.1.0.29
2018-10-13T09:06:41.3820602Z PackageDeployer Information: 8 : Deployment Target Organization Uri: https://disneytest.api.crm5.dynamics.com/XRMServices/2011/Organization.svc
2018-10-13T09:06:41.3827571Z PackageDeployer Information: 8 : Deployment Target Organization Time marker: 10/13/2018 09:06:41 +00:00
2018-10-13T09:06:41.3833677Z PackageDeployer Information: 8 : User Code Execution : OP=InitializeExtension : Status=Execute
2018-10-13T09:06:41.3842041Z PackageDeployer Information: 8 : User Code Execution : OP=InitializeExtension : Status=Complete : Duration=00:00:00.0007932
2018-10-13T09:06:41.3897086Z PackageDeployer Information: 8 : Completed Config Reading process
2018-10-13T09:06:41.5960120Z PackageDeployer Information: 8 : ************** Solution IMPORT *****************
2018-10-13T09:06:41.5969758Z PackageDeployer Information: 8 : Starting Processing Of Solution: AsyncRequestResponseSample(AsyncRequestResponseSample), Version: 1.0.0.12, PackageVersion: 8.2
2018-10-13T09:06:41.8600649Z PackageDeployer Information: 8 : AsyncRequestResponseSample : User Code Execution : OP=OverrideSolutionImportDecision : Status=Execute
2018-10-13T09:06:41.8607891Z PackageDeployer Information: 8 : AsyncRequestResponseSample : User Code Execution : OP=OverrideSolutionImportDecision : Status=Complete : Duration=00:00:00.0008888
2018-10-13T09:06:41.8614298Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Processing Solution - Inbound version: 1.0.0.12 - Deployed Version 0.0.0.0, System Determined Import Action: Import
2018-10-13T09:06:41.8620224Z PackageDeployer Information: 8 : AsyncRequestResponseSample - ImportSolution - Initial solution install of version 1.0.0.12
2018-10-13T09:06:41.8678520Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Importing solution for AsyncRequestResponseSample Version: 1.0.0.12
2018-10-13T09:06:41.8763666Z PackageDeployer Information: 8 : User Code Execution : OP=PreSolutionImport : Status=Execute
2018-10-13T09:06:41.8770261Z PackageDeployer Information: 8 : User Code Execution : OP=PreSolutionImport : Status=Complete : Duration=00:00:00.0008034
2018-10-13T09:06:42.2369255Z PackageDeployer Information: 8 : ImportSolution - Async Supported = True
2018-10-13T09:06:42.2375299Z PackageDeployer Information: 8 : DeleteAndPromote - Async Supported = True
2018-10-13T09:06:42.2467783Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Executing Solution Import - NormalSolutionLoad 
2018-10-13T09:08:42.8048351Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Fetching Data
2018-10-13T09:08:43.0370598Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Import Progress is : 93.0232558139535
2018-10-13T09:08:43.0741490Z PackageDeployer Information: 8 : AsyncRequestResponseSample Solution Import Result = UNKNOWN - Duration: 00:02:01.4757043
2018-10-13T09:08:48.0762843Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Fetching Data
2018-10-13T09:08:48.7418039Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Import Progress is : 93.0232558139535
2018-10-13T09:08:48.7418552Z PackageDeployer Information: 8 : AsyncRequestResponseSample Solution Import Result = UNKNOWN - Duration: 00:02:01.4757043
2018-10-13T09:08:53.7355062Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Fetching Data
2018-10-13T09:08:53.7355745Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Import Progress is : 93.0232558139535
2018-10-13T09:08:53.7355886Z PackageDeployer Information: 8 : AsyncRequestResponseSample Solution Import Result = UNKNOWN - Duration: 00:02:01.4757043
2018-10-13T09:08:58.3240620Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Fetching Data
2018-10-13T09:08:58.4289687Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Import Progress is : 93.0232558139535
2018-10-13T09:08:58.4298551Z PackageDeployer Information: 8 : AsyncRequestResponseSample Solution Import Result = UNKNOWN - Duration: 00:02:01.4757043
2018-10-13T09:09:03.4431295Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Fetching Data
2018-10-13T09:09:03.5535646Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Import Progress is : 93.0232558139535
2018-10-13T09:09:03.5543512Z PackageDeployer Information: 8 : AsyncRequestResponseSample Solution Import Result = UNKNOWN - Duration: 00:02:01.4757043
2018-10-13T09:09:08.5558823Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Fetching Data
2018-10-13T09:09:08.6514390Z PackageDeployer Information: 8 : AsyncRequestResponseSample - Import Progress is : 100
2018-10-13T09:09:08.6524505Z PackageDeployer Information: 8 : AsyncRequestResponseSample Solution Import Result = success - Duration: 00:02:01.4757043
2018-10-13T09:09:09.3771999Z PackageDeployer Information: 8 : Completed Processing Of Solution: AsyncRequestResponseSample(AsyncRequestResponseSample), Version: 1.0.0.12, PackageVersion: 8.2 , Duration: 00:02:01.4757043
2018-10-13T09:09:09.3777925Z PackageDeployer Information: 8 : ************** Solution IMPORT COMPLETE *****************
2018-10-13T09:09:09.3787505Z PackageDeployer Information: 8 : ************** Solution PUBLISH *****************
2018-10-13T09:10:53.1781454Z PackageDeployer Information: 8 : ************** Solution PUBLISH COMPLETE *****************
2018-10-13T09:10:53.3867787Z PackageDeployer Information: 8 : ************** BeforeImportStage *****************
2018-10-13T09:10:53.3875124Z PackageDeployer Information: 8 : User Code Execution : OP=BeforeImportStage : Status=Execute
2018-10-13T09:10:53.3882302Z PackageDeployer Information: 8 : User Code Execution : OP=BeforeImportStage : Status=Complete : Duration=00:00:00.0001391
2018-10-13T09:10:53.3889918Z PackageDeployer Information: 8 : ************** BeforeImportStage Complete *****************
2018-10-13T09:10:53.3925504Z PackageDeployer Information: 8 : User Code Execution : OP=DataImportBypass : Status=Execute
2018-10-13T09:10:53.3932826Z PackageDeployer Information: 8 : User Code Execution : OP=DataImportBypass : Status=Complete : Duration=00:00:00.0007398
2018-10-13T09:10:53.6031244Z PackageDeployer Information: 8 : User Code Execution : OP=DataImportBypass : Status=Execute
2018-10-13T09:10:53.6037263Z PackageDeployer Information: 8 : User Code Execution : OP=DataImportBypass : Status=Complete : Duration=00:00:00.0008462
2018-10-13T09:10:53.6217829Z PackageDeployer Information: 8 : User Code Execution : OP=OverrideDataImportSafetyChecks : Status=Execute
2018-10-13T09:10:53.6225725Z PackageDeployer Information: 8 : User Code Execution : OP=OverrideDataImportSafetyChecks : Status=Complete : Duration=00:00:00.0007291
2018-10-13T09:10:53.6595713Z PackageDeployer Information: 8 : User Code Execution : OP=OverrideDateMode : Status=Execute
2018-10-13T09:10:53.6609020Z PackageDeployer Information: 8 : User Code Execution : OP=OverrideDateMode : Status=Complete : Duration=00:00:00.0013676
2018-10-13T09:10:53.6659066Z PackageDeployer Information: 8 : User Code Execution : OP=OverrideDataTimestamp : Status=Execute
2018-10-13T09:10:53.6659158Z PackageDeployer Information: 8 : User Code Execution : OP=OverrideDataTimestamp : Status=Complete : Duration=00:00:00.0007300
2018-10-13T09:11:01.5394337Z PackageDeployer Information: 8 : User Code Execution : OP=AfterPrimaryImport : Status=Execute
2018-10-13T09:11:01.7460380Z PackageDeployer Error: 2 : Message: User Code Execution : OP=AfterPrimaryImport : Status=Failed to execute Post Import Actions
2018-10-13T09:11:01.7677011Z Source	: DeploymentPackage
2018-10-13T09:11:01.7721598Z Method	: AfterPrimaryImport
2018-10-13T09:11:01.7722083Z Date	: 9:11:01 AM
2018-10-13T09:11:01.7722333Z Time	: 10/13/2018
2018-10-13T09:11:01.7722566Z Error	: Method not found: 'Microsoft.Xrm.Tooling.Connector.CrmServiceClient Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageExtentionBase.ImportExtension.get_CrmSvc()'.
2018-10-13T09:11:01.7722790Z Stack Trace	: at PackageDeployer.PackageTemplate.AfterPrimaryImport()
2018-10-13T09:11:01.7723081Z    at Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageCore.ImportCode.BaseImportCustomizations.ExecutePostImportActions()
2018-10-13T09:11:01.7723265Z ======================================================================================================================
2018-10-13T09:11:01.7723437Z 
2018-10-13T09:11:01.7723805Z PackageDeployer Information: 8 : ****** PACKAGE DEPLOYMENT PROCESS COMPLETED. Result:FAILED  Duration:00:04:20.5436808 ******
2018-10-13T09:11:01.7724022Z PackageDeployer Information: 8 : ****** PACKAGE DEPLOYMENT PROCESS COMPLETED. Result:FAILED  Duration:00:04:20.5436808 ******
2018-10-13T09:11:01.8682312Z ##[error]The post-import process failed: Method not found: 'Microsoft.Xrm.Tooling.Connector.CrmServiceClient Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageExtentionBase.ImportExtension.get_CrmSvc()'.
2018-10-13T09:11:02.2691091Z ##[error]Import Failed
2018-10-13T09:11:02.4073609Z ##[section]Finishing: Deploy Dynamics 365 Package and Data using Package Deployer

**Comment by WaelHamze** [comment]
@Amos-lin the tasks works fine for me on a number of packages. What version of SDK is your package using? Might be worth updating to the latest version.

**Comment by WaelHamze** [comment]
Please re-open if you still facing this issue.
